alias:deny("cancel")
alias:enter("exit", "en", "ex")
alias:items("item", "inv", "inventory")
alias:email("mail")
alias:savestats("savestat", "saveme")
alias:time("delay")
alias:helmet("helm", "head")
alias:smoke("rokok", "smoking", "cigarette", "cig", "udud")